rails/lab1/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/books", to: "books#index"
  # get "/books/:id", to: "books#show"
  # Defines the root path route ("/")
  root "books#index"

  resources :books 
  
  
end

rails/lab1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails/lab1/app/models/book.rb
class Book < ApplicationRecord
    validates :name, presence: true, length: {minimum:3}
    validates :price, presence: true
    validates :image,presence: true
    validates :description,presence: true

    belongs_to :user
    
end

rails/lab1/app/models/user.rb
class User < ApplicationRecord
    has_many :books
end

rails/lab1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/lab1/app/controllers/books_controller.rb
class BooksController < ApplicationController

  http_basic_authenticate_with name: "rana", password: "1234", except: [:index, :show]
  
  def index
    @books=Book.all
    p @books 
  end

  def show
    @book= Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create 
    @book=Book.new(book_params)
    @book.user_id=1
    
    if @book.save
      redirect_to @book
    else 
      render :new, status: :unprocessable_entity 
    end
  end

  def edit 
    @book= Book.find(params[:id])
  end

  def update
    @book= Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else 
      render :edit,status: :unprocessable_entity
    end 
  end

  def destroy
    @book= Book.find(params[:id])
    @book.destroy
    redirect_to root_path ,status: :see_other
  end

  private 
  def book_params
    params.require(:book).permit(:name, :image ,:price, :description )
  end
end

rails/lab1/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/lab1/app/helpers/books_helper.rb
module BooksHelper
end

rails/lab1/app/helpers/sessions_helper.rb
module SessionsHelper
end

rails/lab1/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

rails/lab1/app/helpers/users_helper.rb
module UsersHelper
end

rails/lab1/app/views/books/_form.html.erb
<%= form_with model: book do |form|%>
    <div>
        <%= form.label  :name %><br>
        <%= form.text_field :name %><br>
        <% @book.errors.full_messages_for(:name).each do |message| %>
        <div> <%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label  :image %><br>
        <%= form.text_field :image %><br>
        <%= form.file_field :image, class: "form-control " %>
    </div>

    <div>
        <%= form.label  :price %><br>
        <%= form.text_field :price %><br>
        <% @book.errors.full_messages_for(:price).each do |message| %>
        <div> <%= message %> </div>
        <% end %>
    </div>

    <div>
        <%= form.label  :description %><br>
        <%= form.text_field :description %><br>
    </div>
   <div>
        <%= form.label  :user_id %><br>
        <%= form.text_field :user_id %><br>
        <% @book.errors.full_messages_for(:user_id).each do |message| %>
        <div> <%= message %> </div>
        <% end %>
    </div>
    <div>
        <%= form.submit %>
        
    </div>

<%end%>

rails/lab1/app/views/books/edit.html.erb
<h1>Edit <h1>
<%= render "form" ,book: @book %> 

rails/lab1/app/views/books/index.html.erb
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<h1>Books</h1>
<%= link_to "create new book" ,new_book_path %>
<table class="table">
  
    <tr>
      
      <th scope="col">Name</th>
      <th scope="col">Image</th>
      <th scope="col">Price</th>
      <th scope="col">Created_at</th>
      <th>Updated_At</th>
      <th>Action</th>
      <th>created By</th>
    </tr>
  </thead>
  <tbody>
    
    
        <% @books.each do |book| %>
        <tr>
            <td>
                <%= book.name %>
            </td>
            <td>
                <%= book.image %>
            </td>
            <td>
                <%= book.price %>
            </td>
           
            <td>
                <%= book.created_at %>
            </td>
            <td>
                <%= book.updated_at %>
            </td>
            <td>
                <a href="<%=book_path(book) %>" class="btn btn-primary">Show</a>
                <%# <%=link_to book.name,book %> 
                <a href="<%=edit_book_path(book)%>" class="btn btn-success">update</a>
                <a  class="btn btn-danger"
                 <%= link_to "Delete", book_path(book), data: {
               turbo_method: :delete,
               turbo_confirm: "Are you sure?"
             } %> 
                </a>
                
            </td>

            <td>
                <%= book.user.name %>
            </td>
        
        </tr>
        
    </tbody>

        <% end %>
</table>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

rails/lab1/app/views/books/new.html.erb
<h1> New Book </h1>

<%= render "form" ,book: @book %>

<%= link_to "Back" , root_path(@book) %> 

rails/lab1/app/views/books/show.html.erb
<h1> <%= @book.name%></h1>
<p>  <%= @book.description%> </p>

<%= link_to "Edit" ,edit_book_path(@book) %>

<%= link_to "Destroy", book_path(@book), data:{
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
    } %>


<%= link_to "Back" , root_path(@book) %> 

rails/lab1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>